name: File linting

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Linting changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      - name: Lint all changed files
        run: |
          error_messages=()
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # ensure no BOM is present
            if [[ $(head -c 3 "$file") == $'\xef\xbb\xbf' ]]; then
              error_messages+=("File $file has a BOM")
            fi
          
            # other checks?
            # ...
          done
          
          # print errors if any
          if [[ ${#error_messages[@]} -ne 0 ]]; then
            echo "Errors found in commit"
            for error_message in "${error_messages[@]}"; do
              echo "  $error_message"
            done
          exit 1
          fi
          
          exit 0
